apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata: 
  name: autoscaling

spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:


  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70


  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60
    

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-laravel



